Add meson makefile
sagiegurari/cargo-make-tasks pull request #1
Opened 2021-06-19 03:47 UTC by TiceCosmos

[The Meson Build system](https://mesonbuild.com/)

2021-06-20 06:38 UTC, sagiegurari requested changes
@TiceCosmos amazing work. never used meson before so my knowledge there is a bit limited, but overall looks really great and would love to merge it.

2021-06-20 06:38 UTC, sagiegurari commented on src/meson.toml
> +
can we remove double spaces to a single one?

2021-06-20 06:38 UTC, sagiegurari commented on src/meson.toml
> +BUILDDIR = "./target/debug"
can we make env vars that are used by cargo-make to start with CARGO_MAKE_MESON_?
that way we know whats cargo-make and what is specifically owned by some tool.

2021-06-20 06:38 UTC, sagiegurari commented on src/meson.toml
> +[tasks.setup-development]
instead of writing this task twice with just different args, put in the profile some args flag for the setup, and then expand it using functions (see docs).
that way you have only the task defined once tasks.setup and it will work for all profiles.

2021-06-20 06:38 UTC, sagiegurari commented on src/meson.toml
> +[env.development]
lets drop it and put everything in dev as default env vars.
and production will override it.
that way, if a user doesn't specify the profile or puts a different profile name, it will default to dev.

2021-06-20 06:38 UTC, sagiegurari commented on src/meson.toml
> +[tasks.setup]
we can drop this task if we merge the setup as suggested before

2021-06-20 06:38 UTC, sagiegurari commented on src/meson.toml
> +command = "meson"
how about an install task to install-meson meson and other tools needed?

2021-06-20 06:38 UTC, sagiegurari commented on src/meson.toml
> +output = exec ninja -C ${BUILDDIR} -t graph
duckscript exec command has a file on error flag so in case of error, the task will fail. suggest to add it.

2021-06-22 03:47 UTC, TiceCosmos commented on src/meson.toml
> +command = "meson"
`pip3 install meson`

2021-06-23 14:36 UTC, sagiegurari requested changes
looks awesome. few small stuff and we are good to go.

2021-06-23 14:36 UTC, sagiegurari commented on src/meson.toml
> +if not eq ${output.code} "0"
no need to check code since it if it not 0, it will break and exit cargo-make

2021-06-23 14:36 UTC, sagiegurari commented on src/meson.toml
> +[tasks.setup]
i wonder if in setup, you want to call install-meson? wdyt?

2021-06-24 09:33 UTC, sagiegurari commented on src/meson.toml
> +
don't you want to add here
CARGO_MAKE_MESON_ARGS = { unset = true }
so the coverage args won't be used in production profile?

2021-06-24 09:33 UTC, sagiegurari approved these changes

2021-06-24 09:34 UTC, sagiegurari commented
@TiceCosmos looks great. i have approved it.
i just got 1 last question about CARGO_MAKE_MESON_ARGS there, so tell me what you think and then i'll merge the PR.

2021-06-25 06:00 UTC, TiceCosmos commented on src/meson.toml
> +
In most cases, `CARGO_MAKE_MESON_ARGS` is same in different profile.

2021-06-25 14:00 UTC, sagiegurari commented
@TiceCosmos merging. thanks a lot for the PR!!!

2021-06-25 14:00 UTC, merged